# lazy_image:
    # It is recommended to cache the generated BlurHash for performance reasons, to avoid generating it for each request.
    # https://symfony.com/bundles/ux-lazy-image/current/index.html#performance-considerations
    # cache: cache.lazy_image

framework:
    cache:
        # pools:
            # cache.lazy_image: 
                # If possible, prefer to use a cache adapter that is not cleared between deployments, like "cache.adapter.redis"
                # adapter: cache.app
