#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# requires installing the 'sensio/framework-extra-bundle:^3.0' package
#controllers:
#    resource: ../src/Controller/
#    type: annotation
