monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
            channels: ["!app"]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        app:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-app.log"
            channels: ["app"]
