tchoulom_view_counter:
    view_counter:
        view_strategy: daily_view
    statistics:
        use_stats: false
        stats_file_name: stats
        stats_file_extension:
    #geolocation:
    #    service_id: # Your Geolocator service ID
