services:
    SensioLabs\Security\Crawler:
        public: false

    SensioLabs\Security\SecurityChecker:
        arguments: ['@SensioLabs\Security\Crawler']
        public: false

    SensioLabs\Security\Command\SecurityCheckerCommand:
        arguments: ['@SensioLabs\Security\SecurityChecker']
        public: false
        tags:
            - { name: console.command, command: 'security:check' }
